### ISSUE TITLE
Fix Upload Time in Stream Tester

### ISSUE THREAD

**Issue by leszko** [livepeer/stream-tester#138]
The upload time is not logged in the Stream Tester data. It's always `0.0`.

For example, https://interptr-latest-test-streams.vercel.app/?address=0x9d5611bf0dadddb4441a709141d9229d7f6b3e47, always shows only `0.0` in the `Upload Time` column.

I believe the bug is related to the [Per-stream metrics PR](https://github.com/livepeer/go-livepeer/pull/2238), which adds the transcoder URI to the metrics.

**Comment by hthillman** [comment]
cc @iameli

**Comment by papabear99** [comment]
I can add that this behavior began when Livepeer migrated to L2.  Not sure if it is just a coincidence that it began at the same time but you can see from this screenshot of my test scores that it began the day after the migration.
![TestStreamUpload2](https://user-images.githubusercontent.com/89408276/170585678-d9fa997f-b921-418f-a19c-be357bec3722.png)

On (very) rare occasions the test results will show a value for the upload time but 99%+ of the time the upload time value is combined into the transcode time.
![TestStreamUpload](https://user-images.githubusercontent.com/89408276/170585974-16c5bdd2-042b-4256-b704-a88d54e01d79.png)

**Comment by leszko** [comment]
FYI: I already know what's wrong with the upload time. Will send a fix soon.
