### ISSUE TITLE
Find the best way to use stream-tester to test Mist server that is streaming Picarto streams

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/stream-tester#25]

**Comment by ericxtang** [comment]
@darkdarkdragon and I worked together a bit on this today.  We encountered a few different errors in the `stream-tester`, and @darkdarkdragon is doing some investigation to figure out the steps needed to remove these errors, so we can set up a staging end-to-end environment for Mist (similar to what we have for Wowza).

**Comment by wohlner** [comment]
To do: break this up into smaller ticket today @darkdarkdragon  thanks

**Comment by darkdarkdragon** [comment]
Decided to calculate success rate of Picarto streams using only output - count number of segments in source HLS stream and compare it to number of segments in transcoded HLS stream. 
So sub-tasks:
- [ ] Teach stream-tester to start Picarto streams and find URL of HLS stream to be pulled from
- [ ] Teach stream-tester to calculate success rate using only output
- [ ] Make deployment with stream tester or testdriver to periodically run Picarto tests
