### ISSUE TITLE
stream-tester sometimes doesn't read back its response body, maybe?

### ISSUE THREAD

**Issue by iameli** [livepeer/stream-tester#29]
Forking discussion from internal Discord channel — this is what I've found for at least one 400 response, but perhaps this is just what happened when an instance was restarting or some such?

https://my.papertrailapp.com/groups/16613582/events?focus=1164038057298141210&selected=1164038057298141210

```
2020-02-11T23:58:42.000Z nginx-ingress-controller-74956b95cf-8vxwp chi 2020/02/11 23:58:42 
[info] 396#396: *217918 client prematurely closed stream: only 0 out of 387468 bytes of request body 
received, client: 10.140.19.8, server: chi-broadcaster-charmander.livepeer-ac.live, request: "POST 
/live/af1e01d8-6fb0-42c3-b7a5-9b20cada2e0c/44.ts HTTP/2.0", host: "chi-broadcaster-
charmander.livepeer-ac.live"
```

**Comment by darkdarkdragon** [comment]
@iameli Cool, we hit a bug in Golang's HTTP library 😄 
https://github.com/golang/go/issues/32441
There is open PR with the fix https://golang.org/cl/210123 , but it sits there for a while, so it is unknown when it will get to the Golang's release.
Will disable HTTP2 for the stream tester deployment for now, let see how it will go.

**Comment by iameli** [comment]
@darkdarkdragon Yep, this seems to be fixed. Thanks!
