### ISSUE TITLE
HA streams double when played back from origin server

### ISSUE THREAD

**Issue by iameli** [livepeer/stream-tester#43]
The MistUtilLoad stuff is working well when you playback from one of the other machines in the cluster. When you play back from the origin, there are some bugs.

If I'm streaming into mist-server-0, incoming requests for mist-server-1 and mist-server-2 work perfectly, returning this playlist

![image](https://user-images.githubusercontent.com/257909/86615376-3af7a180-bf69-11ea-9702-d0ddebff03e8.png)

But if I hit the origin server, mist-server-0, and want playback there... every stream is doubled; each rendition shows up twice. It's like its serving both its local origin stream as well as another load-balanced stream from within the cluster?

![image](https://user-images.githubusercontent.com/257909/86615561-74301180-bf69-11ea-833d-87f4d2ee1c31.png)

**Comment by darkdarkdragon** [comment]
Fixed by 560cf15db521ad351cdc31f0f2ca536a9e05f304
