### ISSUE TITLE
Modify stream tester to work with the Wowza flow

### ISSUE THREAD

**Issue by ericxtang** [livepeer/stream-tester#5]

**Comment by ericxtang** [comment]
We are seeing a timestamp issue.  Sometimes the media playlist name changes, and the new media playlist contains skipped segments with timestamp that's earlier than the previous segment.

**Comment by darkdarkdragon** [comment]
Writing here design for needed changes in stream-tester:
1. Should fail immediately if there is more than one media stream with same resolution - we can only distinguish streams by resolution when streams change, so we can't support this case.
2. Should wait for stream to start, with timeout.
3. Should track media streams by resolution, handling stream switch.
4. If no new segments appearing after timeout (8 sec) - stop streaming and report failure.
5. Should parse each received segment - stop streaming and report failure if can't parse.
6. Should check for gaps in timestamps - if there is one, stop streaming and report failure.
7. Should save time at which segment appears in playlist, and check if timestamps of segments that appears at the same time in different media streams match. If differs for more than two seconds - report failure and stop streaming.
8. If no failures, periodically report stats to Discord.

**Comment by darkdarkdragon** [comment]
Work to do:
Write new version of `m3utester`.
1. Should track media streams by resolution.
2. Should get reports about errors from media downloaders.
3. Get reports from `mediaDownloader` about each downloaded segment - time of appearance, PTS, segment's length. Saves it sorted by the time of appearance.
4. Periodically compares PTSes of corresponding (by the time of appearance) segments in different media streams, report error if too big.

Write new `mediaDownloader`
1. Should handle media stream switches
2. Parse each downloaded segment, report errors to `m3utester`
3. Continuously check stream for gaps, report errors to `m3utester`
4. Stops and reports error if no new segments for some time.
