### ISSUE TITLE
Check and see if output is coming back faster than real time in the automated tests

### ISSUE THREAD

**Issue by ericxtang** [livepeer/stream-tester#6]
We can start by checking latency

**Comment by darkdarkdragon** [comment]
We're streaming RTMP into Wowza, but getting HLS segments back. That means that we don't have clear way to mark point at which we sent segment to check how long it took to receive it back.
Possible way to do it:
When streaming, save time at which we sent each keyframe (along with it's PTS).
When received segment, take it's starting PTS and length and find when last keyframe of this segment was sent to Wowza. That way we will find how long it took from sending segment's last frame to receive it back. This will be our latency. We divide it by segment's length - it will be our 'speed' ratio - if less than one - than it's faster than realtime.

**Comment by j0sh** [comment]
Do we have a reliable way of correlating the input and output PTS? There is going to be a timebase conversion (1khz FLV -> 90khz mpegts) and maybe some adjustments for framerate.

**Comment by darkdarkdragon** [comment]
Need to check, but I hope that difference will be small enough and will not make correlation too hard.

**Comment by j0sh** [comment]
It's probably OK  if the test cases are consistently the same, but I suspect it may be a lot harder with more unpredictable inputs / outputs / etc
