### ISSUE TITLE
Mist integration improvement

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/stream-tester#66]
**Problem**:

Then there is a lot of stream objects (more than 100) created in the Mist - it takes considerable time to create new stream object in Mist (took almost two minutes during the load test).

**Proposed solution**:
We need to handle start of the new streams without calling Mist API.
For that we could leverage Mist's wildcard streams.

- [ ] In Mist static configuration we will add stream called `v1base`. Configure it with wildcards enabled and Livepeer transcoding with custom Livepeer API url set to `https://livepeer.com/api/stream/v1base/` 

- [ ] mist-api-connector will rewrite incoming streams from `rtmp://mist/streamKey` to the `rtmp://mist/v1base+playbackId` and also in the Traefik config it will add rule to rewrite incoming `/hls/playbackId` paths to the `/hls/v1base+playbackId`

- [ ] Mist will be creating new Livepeer API streams using url `https://livepeer.com/api/stream/v1base/`  with name set to `v1base+playbackId`. So, Livepeer API `/stream/v1base/stream` handler will check if name matches `v1base+playbackId` pattern - if so, it will look into db for the stream with playbackId, and will create session object with transcoding settings taken from the parent object.

**Comment by iameli** [comment]
This sounds great, just want to call out one thing...

> it takes considerable time to create new stream object in Mist (took almost two minutes during the load test).

Totally absurd. Servers all had plenty of CPU, RAM, Disk IO. Can't imagine why this would take so long, but then I think back to this thing

![image](https://user-images.githubusercontent.com/257909/101419908-e2c12480-38a5-11eb-86a5-496953e753f0.png)

And think maybe Mist is fork bombing or some such.

**Comment by darkdarkdragon** [comment]
> Totally absurd. 

Yes. And we have two options: wait for Jeron to fix it or change our system.

**Comment by darkdarkdragon** [comment]
Done in ed9656d17af4a92452821b20dcda79f64456428a
