### ISSUE TITLE
mist-api-connector: create one service per mist server

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/stream-tester#71]
Currently for every stream there is separate 'service' key gets created in Consul. It is not necessary because most of them are duplicates.

Need to change to create only one service per Mist server.
Each mist-api-connector instance is configured with URL of the Mist server to which request should be routed to.
We can create service with name based on this URL and use it in all routes - that way number of services will be equal to number of Mist instances.

**Comment by iameli** [comment]
Cool. Probably no harm in not cleaning those up either, they'll always be the same with the same address.

**Comment by wohlner** [comment]
This is very old and the status is "in review." Neither @iameli nor I see a PR. Is there one?

**Comment by wohlner** [comment]
If not, no worries. Per conversation with @iameli today, this is not something we want to do right now.

**Comment by darkdarkdragon** [comment]
This is in the production for a long time.
